spring:
  ai:
    vectorstore:
      redis:
        uri: ${REDIS_URI}
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: "gpt-4o-mini"
  profiles:
    include: SECRET-KEYS